#!/bin/bash

EXE=./holyc

assert() {
  expected="$1"
  input="$2"

  echo "$input" | $EXE > tmp
  actual=$(cat tmp)
  rm ./tmp

  if [ "$actual" = "$expected" ]; then
    echo "$input => $actual"
  else
    echo "$input => $expected expected, but got $actual"
    exit 1
  fi
}

# single numbers
assert 0 0
assert 42 42

# +, -
assert 21 "5+20-4"
assert 4 "1+3"
assert 4 "6-2"

echo OK
