---
name: lib/c

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: make -C lib/c

      - name: test
        run: make -C lib/c test
